name: CI

on: [push]

jobs:
  build-events:
    name: Event Handler Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: events
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Unit Test
        run: yarn test

      - name: Lint
        run: yarn lint

  tag:
    name: Tag the release
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build-events]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: tag
        id: tag
        uses: tcpl/semver-tag-creator-action@1.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          major-version: 1
